name: Test execution CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci install
        
      - name: Execute tests
        run: npm test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        if: ${{ always() }} # if you don't mention this, then this step will never run because 'npm test' will EXIT the process!
        with:
          name: code-coverage-report
          path: coverage/
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 
          
      - name: Archive the test results
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-report
          path: test-report/
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 
